---
- name: Install mysql-python
  pip:
    name:
      - setuptools
      - pymysql

- name: Set log output to FILE
  mysql_variables:
    variable: log_output
    value: "FILE"
    login_user: "{{ slowquery_db_user | default(omit) }}"
    login_password: "{{ slowquery_db_password | default(omit) }}"
    login_unix_socket: "{{ slowquery_unix_socket }}"

- block:

    - name: Enable slow query log
      mysql_variables:
        variable: slow_query_log
        value: "ON"
        login_user: "{{ slowquery_db_user | default(omit) }}"
        login_password: "{{ slowquery_db_password | default(omit) }}"
        login_unix_socket: "{{ slowquery_unix_socket }}"

    - name: Set slow query file
      mysql_variables:
        variable: slow_query_log_file
        value: "{{ slowquery_log_file }}"
        login_user: "{{ slowquery_db_user | default(omit) }}"
        login_password: "{{ slowquery_db_password | default(omit) }}"
        login_unix_socket: "{{ slowquery_unix_socket }}"

    - name: Set slow query threshold
      mysql_variables:
        variable: long_query_time
        value: "{{ slowquery_threshold }}"
        login_user: "{{ slowquery_db_user | default(omit) }}"
        login_password: "{{ slowquery_db_password | default(omit) }}"
        login_unix_socket: "{{ slowquery_unix_socket }}"

  when: slowquery_enable

- block:

    - name: Disable slow query log
      mysql_variables:
        variable: slow_query_log
        value: "OFF"
        login_user: "{{ slowquery_db_user | default(omit) }}"
        login_password: "{{ slowquery_db_password | default(omit) }}"
        login_unix_socket: "{{ slowquery_unix_socket }}"

  when: not slowquery_enable
