---
- name: Source files are deployed
  synchronize:
    src: "../webapp"
    dest: "{{ deploy_app_dir }}"
    compress: yes
    archive: no
    delete: yes
    recursive: yes
    mode: push
    rsync_opts:
      - --exclude=__pycache__/
      - --exclude=.venv/
      - --exclude=venv/
      - --exclude=node_modules/
      - --exclude=vendor/
      - --exclude=.git/
      - --exclude=public/
  become: no

# - name: Bundle install
#  bundler:
#    state: present
#    chdir: "{{ deploy_app_rb_root | default(deploy_app_dir + '/ruby') }}"
#    executable: "/home/isucon/local/ruby/bin/bundler"
#  become_user: isucon
#  become: yes

#- name: App binary is built
#  command: "/home/isucon/local/go/bin/go build -o {{ app_name }}"
#  args:
#    chdir: "{{ deploy_app_dir }}/go"
#  environment:
#    GOOS: "linux"
#    GOARCH: "amd64"
#    CGO_ENBALED: "0"

- name: Restart webapp
  systemd:
    name: "{{ app_unit_name }}"
    enabled: yes
    state: restarted
  become: yes
