---
web:
  hosts:
    isu1:
    isu2:
    isu3:
  children:
    nginx:
      hosts:
        isu1:
        isu2:
        isu3:
db:
  hosts:
    isu1:
    isu2:
    isu3:
redis:
  hosts:
    isu1:
    isu2:
    isu3:
