---
- hosts: web
  roles:
    - name: deploy_configs
    - name: deploy_webapp
    - name: restart_service
      vars:
        restart_services:
          - name: "{{ app_unit_name }}"
            daemon_reload: yes
