---
- hosts: web
  roles:
    - name: deploy_configs
      vars:
        deploy_config_files:
          - /etc/systemd/system/isuports.service
    - name: deploy_webapp
    - name: restart_service
      vars:
        restart_services:
          - name: "{{ app_unit_name }}"
            daemon_reload: yes
