---
- hosts: all
  roles:
    - name: deploy_configs
      vars:
        deploy_config_files:
#          - /etc/nginx/sites-available/isucari.conf
          - /etc/nginx/nginx.conf

    - name: restart_service
      vars:
        restart_services:
          - name: nginx
            reload: yes
